from django import forms
from .models import CheckList, Car
from django.utils.translation import gettext_lazy as _

class CheckListForm(forms.Form):
    date = forms.DateField(widget=forms.DateInput(format="%Y-%m-%d", attrs={'type': 'date'}), label=_('Date'))
    car = forms.ModelChoiceField(label=_('Select plate number'), queryset=Car.objects.all())
    driver = forms.CharField(label=_('Put driver name'), max_length=25)
    fuel_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES, attrs={'type': 'inline'}))
    fuel_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    oil_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    oil_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    brake_fluid_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    brake_fluid_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    cooling_fluid_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    cooling_fluid_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    windshield_fluid_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    windshield_fluid_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    headlights_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    headlights_comment =forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    revers_lights_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    revers_lights_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    turn_stop_ind_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    turn_stop_ind_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    wheel_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    wheel_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    clutch_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    clutch_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    brake_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    brake_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    monitor_device_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    monitor_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    heater_cond_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    heater_cond_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    wipers_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    wipers_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    beep_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    beep_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    beep_reverse_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    beep_reverse_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    gps_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    gps_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    dvr_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    dvr_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    battery_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    battery_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    inside_out_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    inside_out_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    mirrors_glass_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    mirrors_glass_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    seat_belts_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    seat_belts_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    tires_press_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    tires_press_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    disks_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    disks_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    number_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    number_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    wheel_nuts_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    wheel_nuts_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    extingusher_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    extingusher_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    first_aid_kit_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    first_aid_kit_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    car_tools_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    car_tools_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    spare_wheel_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    spare_wheel_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    warning_triangle_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    warning_triangle_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    tow_rope_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    tow_rope_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    wheel_chocks_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    wheel_chocks_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    walkie_talkie_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    walkie_talkie_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    reflective_vest_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    reflective_vest_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    scraper_brush_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    scraper_brush_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    driver_license_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    driver_license_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    car_docs_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    car_docs_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    cargo_docs_mark = forms.CharField(widget=forms.RadioSelect(choices=CheckList.CHOICES))
    cargo_docs_comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=40,  required=False)
    corrective_actions = forms.CharField(widget=forms.Textarea(attrs={'rows': 3,'style': 'width: 100%; height: 100%;'}), max_length=100,  required=False)
    

    

