# Generated by Django 5.0.7 on 2024-07-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Plate number')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_list_app.direction')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('driver', models.CharField(max_length=25, verbose_name='Driver_name')),
                ('fuel_mark', models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], max_length=1)),
                ('fuel_comment', models.CharField(max_length=40, verbose_name='Comment')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_list_app.car')),
            ],
        ),
    ]
