# Generated by Django 5.0.7 on 2024-07-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0002_car_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='fuel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')]),
        ),
    ]
