# Generated by Django 5.0.7 on 2024-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0003_alter_checklist_fuel_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_comment',
            field=models.CharField(default=1, max_length=40, verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='cooling_fluid_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='cooling_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='oil_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='oil_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='windshield_fluid_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='windshield_fluid_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
            preserve_default=False,
        ),
    ]
