# Generated by Django 5.0.7 on 2024-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0004_checklist_brake_fluid_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='headlights_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='headlights_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='revers_lights_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='revers_lights_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='turn_stop_ind_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='turn_stop_ind_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
    ]
