# Generated by Django 5.0.7 on 2024-07-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0005_checklist_headlights_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='battery_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='battery_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_reverse_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='beep_reverse_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='brake_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='clutch_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='clutch_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dvr_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='dvr_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='gps_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='gps_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heater_cond_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='heater_cond_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='monitor_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='monitor_device_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wipers_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wipers_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
    ]
