# Generated by Django 5.0.7 on 2024-07-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0006_checklist_battery_comment_checklist_battery_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='disks_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='disks_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inside_out_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inside_out_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='mirrors_glass_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='mirrors_glass_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='number_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='number_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='seat_belts_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='seat_belts_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tires_press_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tires_press_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_nuts_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_nuts_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
    ]
