# Generated by Django 5.0.7 on 2024-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list_app', '0007_checklist_disks_comment_checklist_disks_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='car_tools_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='car_tools_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='extingusher_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='extingusher_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='first_aid_kit_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='first_aid_kit_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reflective_vest_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reflective_vest_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='scraper_brush_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='scraper_brush_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='spare_wheel_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='spare_wheel_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tow_rope_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tow_rope_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='walkie_talkie_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='walkie_talkie_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='warning_triangle_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='warning_triangle_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_chocks_comment',
            field=models.CharField(default=None, max_length=40, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='wheel_chocks_mark',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO'), (2, 'N/A')], default=None),
        ),
    ]
